### ISSUE TITLE
libiconv.so: has text relocations error

### ISSUE THREAD

**Issue by bbeckk** [littlemonkeyltd/QRScanner#8]
I have recently updated the app that uses QRScanner lib and has the following bug that cause app to crash. The error occured in nougat nokia 5 device. I checked the previous version of the app which works fine.

`02-08 16:24:58.792 592-592/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.capitaleyenepal.lenovo, PID: 592
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.capitaleyenepal.lenovo-2/lib/arm/libiconv.so: has text relocations
at java.lang.Runtime.loadLibrary0(Runtime.java:989)
at java.lang.System.loadLibrary(System.java:1562)
at com.dm.zbar.android.scanner.ZBarScannerActivity.<clinit>(ZBarScannerActivity.java:28)
at java.lang.Class.newInstance(Native Method)
at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by NickoftheSouth** [comment]
I believe this issue was fixed in the most recent update. 
Did you install the Cn1lib file from here, or through the cn1 system? 
There's a chance there version of the lib is out of date.
Try to replace the cn1lib file from the one here and let us know if this issue persists

**Comment by ivanilavsky** [comment]
Hi, I have the same issue with cn1lib from here on device with Android 7.1.2.
On device with Android 5.0.2 it works ok.

**Comment by ivanilavsky** [comment]
When I set build hint android.targetSDKVersion=21 then on first app start (only) the error is shown (see screenshot) but then everything works ok also on A 7.1.2
![warn](https://user-images.githubusercontent.com/5778120/38697270-c7cd19f6-3e91-11e8-8913-7f7a9be7d495.jpg)

**Comment by ivanilavsky** [comment]
I had this issue too with library from cn1 Extensions. I replaced it with cn1lib from here but still no success. I uninstalled qrscanner.cn1lib completely a install it from here once again and now everything works ok.
